import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../providers/ThemeProvider";

/* import { Geist, Geist_Mono } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

import { Roboto, Roboto_Mono } from 'next/font/google'; 
const roboto = Roboto({
  subsets: ['latin'],
  weight: "100"
}); 
const robotoMono = Roboto_Mono({ subsets: ['latin'], });
export const metadata: Metadata = {
  title: "Emanuel Funes  Portfolio 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        /* className={`${geistSans.variable} ${geistMono.variable} antialiased`} */
        className={`${roboto.className} ${robotoMono.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
