import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '../../providers/ThemeProvider'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { NavProvider } from '@/hook/useNavContext'
import { Roboto, Roboto_Mono } from 'next/font/google'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'

const roboto = Roboto({
  subsets: ['latin'],
  weight: '100'
})
const robotoMono = Roboto_Mono({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Emanuel Funes  Portfolio 2025',
  description: 'Generated by create next app'
}

type ParamsType<T> = T extends { locale: string }
  ? T
  : T extends Promise<infer U>
  ? U extends { locale: string }
    ? U
    : never
  : never

interface LayoutProps {
  children: React.ReactNode
  params: ParamsType<any>
  // ... other properties
}
export default async function RootLayout ({ children, params }: LayoutProps) {
  const message = await getMessages()
  const { locale } = await Promise.resolve(params)
  return (
    <html lang={locale}>
      <body
        /* className={`${geistSans.variable} ${geistMono.variable} antialiased`} */
        className={`${roboto.className} ${robotoMono.className} antialiased`}
      >
        <NextIntlClientProvider messages={message}>
          <NavProvider>
            <ThemeProvider>
              <div className='min-h-screen  flex flex-col'>
                <Nav />
                {children}
                <Footer />
              </div>
            </ThemeProvider>
          </NavProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
